# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое страницы')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
