# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171123_0525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'страница', 'verbose_name_plural': 'Страницы'},
        ),
    ]
