# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной', max_length=255, unique=True, verbose_name='Название')),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты (e-mail)')),
                ('link', models.CharField(default='mailto:', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'адрес электронной почты',
                'verbose_name_plural': 'Адреса электронной почты',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Пункт меню')),
                ('order_p', models.PositiveIntegerField(choices=[(0, 'Первая'), (1, 'Вторая'), (2, 'Третья'), (3, 'Четвертая'), (4, 'Пятая'), (5, 'Шестая'), (6, 'Седьмая')], default=0, help_text='Первая позиция - крайняя левая, Шестая - крайняя правая', unique=True, verbose_name='Позиция пункта в меню')),
                ('enabled', models.BooleanField(verbose_name='Отображать в меню')),
                ('link', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^((([a-z]|[0-9])+|([a-z]|\\_)+)|\\/)+$')], verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order_p'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной', help_text='Должно быть: Основной', max_length=255, unique=True, verbose_name='Название')),
                ('number', models.CharField(help_text='Введите номер телефона используя следующий формат: +Х(ХХХ)ХХХ-ХХ-ХХ или X XXX XXX XX XX ', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1}|\\d)(\\ \\d{3}\\ |\\(\\d{3}\\))(\\d{3}\\-\\d{2}\\-\\d{2}|\\d{3}\\ \\d{2}\\ \\d{2})$')], verbose_name='Номер телефона')),
                ('link', models.CharField(default='tel:', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('VK', 'VK'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], max_length=60, verbose_name='Социальная сеть')),
                ('enabled', models.BooleanField(verbose_name='Отображать на страницах сайта?')),
                ('link', models.CharField(max_length=255, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'аккаунт социальной сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
