# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Адрес электронной почты 1', max_length=255, unique=True, verbose_name='Название')),
                ('email', models.CharField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты (e-mail)')),
                ('link', models.CharField(default='mailto:', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'адрес электронной почты',
                'verbose_name_plural': 'Адреса электронной почты',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Номер телефона 1', max_length=255, unique=True, verbose_name='Название')),
                ('number', models.CharField(help_text='Введите номер телефона используя следующий формат: +Х(ХХХ)ХХХ-ХХ-ХХ или X XXX XXX XX XX ', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1}|\\d)(\\ \\d{3}\\ |\\(\\d{3}\\))(\\d{3}\\-\\d{2}\\-\\d{2}|\\d{3}\\ \\d{2}\\ \\d{2})$')], verbose_name='Номер телефона')),
                ('link', models.CharField(default='tel:', max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('VK', 'VK'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], max_length=60, verbose_name='Социальная сеть')),
                ('enabled', models.BooleanField(verbose_name='Отображать на страницах сайта?')),
                ('link', models.CharField(max_length=255, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'аккаунт социальной сети',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
