# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(default='Основной', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='Основной', help_text='Должно быть: Основной', max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
