# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номера телефонов', 'verbose_name_plural': 'Номер телефона'},
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(default='Основной', max_length=255),
        ),
    ]
