# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Пункт меню')),
                ('enabled', models.BooleanField(verbose_name='Отображать в меню')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
