# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171120_0836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номер телефонов', 'verbose_name_plural': 'Номер телефона'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='Номер телефона 1', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
