# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_order_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='order_p',
        ),
    ]
