# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171120_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
    ]
