# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171120_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Адрес электронной почты 1', max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(default='mailto:', max_length=255)),
            ],
            options={
                'verbose_name': 'Адрес электронной почты',
                'verbose_name_plural': 'Адреса электронной почты',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='link',
            field=models.CharField(default='tel:', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='Номер телефона 1', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
