# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171120_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='Адрес электронной почты (e-mail)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='link',
            field=models.CharField(default='mailto:', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(default='Адрес электронной почты 1', max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='Введите номер телефона используя следующий формат: Х (ХХХ) ХХХ ХХ ХХ', max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
