# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menu_order_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order_p',
            field=models.PositiveIntegerField(choices=[('0', 'Первая позиция'), ('1', 'Вторая позиция'), ('2', 'Третья позиция'), ('3', 'Четвертая позиция'), ('4', 'Пятая позиция'), ('5', 'Шестая позиция')], default=0, help_text='Первая позиция - крайняя левая, Шестая - крайняя правая', verbose_name='Позиция пункта в меню'),
        ),
    ]
