# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 11:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171120_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='Введите номер телефона используя следующий формат: +Х(ХХХ)ХХХ-ХХ-ХХ или X XXX XXX XX XX ', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+\\d{1}|\\d)(\\ \\d{3}\\ |\\(\\d{3}\\))(\\d{3}\\-\\d{2}\\-\\d{2}|\\d{3}\\ \\d{2}\\ \\d{2})$')], verbose_name='Номер телефона'),
        ),
    ]
