# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171120_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'https://facebook.com'), ('VK', 'https://vk.com'), ('Instagram', 'https://instagram.com')], max_length=60)),
                ('enabled', models.BooleanField(verbose_name='Отображать на страницах сайта?')),
                ('link', models.CharField(max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
            },
        ),
    ]
