# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171123_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^([a-z]+)$')], verbose_name='Ссылка на страницу'),
        ),
    ]
