# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171123_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(regex='^((([a-z]|[0-9])+|([a-z]|\\_)+)|\\/)+$')], verbose_name='Ссылка на страницу'),
        ),
    ]
