# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20171120_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('vk', 'VK'), ('instagram', 'Instagram')], max_length=60),
        ),
    ]
