# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171121_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальная сеть'},
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Аккаунт'),
        ),
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('vk', 'VK'), ('instagram', 'Instagram'), ('twitter', 'Twitter')], max_length=60, verbose_name='Социальная сеть'),
        ),
    ]
