# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171123_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='order_p',
            field=models.PositiveIntegerField(choices=[(0, 'Первая'), (1, 'Вторая'), (2, 'Третья'), (3, 'Четвертая'), (4, 'Пятая'), (5, 'Шестая'), (6, 'Седьмая')], default=0, help_text='Первая позиция - крайняя левая, Шестая - крайняя правая', unique=True, verbose_name='Позиция пункта в меню'),
        ),
    ]
