# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20171121_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальная сеть'},
        ),
    ]
