# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20171121_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('VK', 'VK'), ('Instagram', 'Instagram'), ('Odnoklassniki', 'Odnoklassniki'), ('Twitter', 'Twitter')], max_length=60, verbose_name='Социальная сеть'),
        ),
    ]
