# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20171125_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img1',
            field=models.ImageField(blank=True, upload_to='img/catalog/', verbose_name='Картинка категории'),
        ),
    ]
