# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20171123_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, upload_to='static/img/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, upload_to='static/img/products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to='static/img/products/%Y/%m/%d'),
        ),
    ]
