# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20171123_1120'),
        ('catalog', '0003_auto_20171123_1900'),
    ]

    operations = [
    ]
