# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:45
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_20171124_0311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('name',), 'verbose_name': 'Каталог', 'verbose_name_plural': 'Каталоги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ManyToManyField(to='catalog.Catalog'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание каталога'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя каталога'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.ImageField(blank=True, upload_to='img/products/%Y/%m/%d', verbose_name='Изображение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.ImageField(blank=True, upload_to='img/products/%Y/%m/%d', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, upload_to='img/products/%Y/%m/%d', verbose_name='Изображение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.PositiveIntegerField(default=1, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=150, verbose_name='Ссылка'),
        ),
    ]
