# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20171124_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catalog',
            field=models.ManyToManyField(to='catalog.Catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ManyToManyField(to='catalog.Catalog', verbose_name='Каталог'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=10, verbose_name='Артикул'),
        ),
    ]
