# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(blank=True, default='Заголовок1', help_text='some help text here', max_length=255, verbose_name='Заголовок1')),
                ('text2', models.CharField(blank=True, default='Заголовок2', help_text='some help text here', max_length=255, verbose_name='Заголовок2')),
                ('button_text', models.CharField(blank=True, default='Текст на кнопке', help_text='help text ', max_length=255, verbose_name='Текст на кнопке')),
                ('banner_img', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
            ],
        ),
    ]
