# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Текст на кнопке', help_text='help text ', max_length=255, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text1',
            field=models.CharField(blank=True, default='Заголовок1', help_text='some help text here', max_length=255, verbose_name='Заголовок1'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text2',
            field=models.CharField(blank=True, default='Заголовок2', help_text='some help text here', max_length=255, verbose_name='Заголовок2'),
        ),
    ]
