# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='text1',
            new_name='title1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='text2',
            new_name='title2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='banner_img',
        ),
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, upload_to=('/home/stp/Projects/tgs-secure/static', 'img/banners/')),
        ),
        migrations.AddField(
            model_name='banner',
            name='site',
            field=models.CharField(choices=[('banner1', 'Баннер 1'), ('banner2', 'Баннер 2'), ('banner3', 'Баннер 3'), ('banner4', 'Баннер 4'), ('banner5', 'Баннер 5'), ('banner6', 'Баннер 6')], default='Баннер 1', max_length=14),
        ),
        migrations.AddField(
            model_name='banner',
            name='style',
            field=models.CharField(blank=True, default='style_11', help_text='help text ', max_length=255, verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='Подзаголовок', help_text='some help text here', max_length=14, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, default='#', help_text='help text ', max_length=255, verbose_name='Ссылка'),
        ),
    ]
