# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20171126_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(blank=True, upload_to='static/img/banners/'),
        ),
    ]
