# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_remove_banner_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-id',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='Главный баннер', max_length=255, unique=True, verbose_name='Уникальное название баннера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Подробности', help_text='Макс. 30 символов', max_length=30, verbose_name='Текст на кнопке'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(help_text='Размер изображения баннера выбирать в пропорции выбранного стиля', unique=True, upload_to='static/img/banners/', verbose_name='Изображение на баннере'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='style',
            field=models.CharField(blank=True, choices=[('style_11', 'Стиль 1: Большой баннер с непрозрачным блоком (560х360)'), ('style_12', 'Стиль 2: Большой баннер с прозрачным блоком (560х360)'), ('style_21', 'Стиль 3: Маленький вертикальный баннер с заголовком внизу (270х360)'), ('style_22', 'Стиль 4: Маленький вертикальный баннер с заголовком вверху (270х360)')], default='Стиль 1', help_text='Выберете один из 4-х видов баннера', max_length=255, verbose_name='Стиль'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='Подзаголовок', max_length=14, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title1',
            field=models.CharField(blank=True, default='Заголовок в', help_text='Верхняя строка заголовка (15 символов)', max_length=15, verbose_name='Первая строка заголовка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title2',
            field=models.CharField(blank=True, default='две строки', help_text='Нижняя строка заголовка (15 символов)', max_length=15, verbose_name='Вторая строка заголовка'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, default='#', help_text='Относительная ссылка на товар, католог, акцию и прочее (например "catalog/women")', max_length=255, verbose_name='Ссылка'),
        ),
    ]
