# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0006_auto_20171126_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('id',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
    ]
